name: Terraform Init

on:
  workflow_dispatch:  # Manual trigger only (same as "trigger: none")

jobs:
  terraform-init:
    runs-on: self-hosted

    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7  # Or whatever version you need

      - name: Terraform Init
        working-directory: ./Environment/QA
        run: |
          terraform init \
            -backend-config="storage_account_name=tfstateaajka" \
            -backend-config="container_name=aajkacontainer" \
            -backend-config="key=statefile" \
            -backend-config="resource_group_name=testrg" \
            -backend-config="subscription_id=${{ env.ARM_SUBSCRIPTION_ID }}" \
            -backend-config="use_azuread_auth=false"
