name: InfraPipleineforAzure.yaml

on: [workflow_dispatch]

jobs:
  terraformjob:
    name: infra-provision
    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2

    - name: Terraform version check
      run: terraform --version

    - name: Azure Authentication
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURECONNECTION }}

    - name: Set Terraform Azure Environment Variables
      run: |
        echo "ARM_CLIENT_ID=${{ fromJson(secrets.AZURECONNECTION).clientId }}" >> $GITHUB_ENV
        echo "ARM_CLIENT_SECRET=${{ fromJson(secrets.AZURECONNECTION).clientSecret }}" >> $GITHUB_ENV
        echo "ARM_SUBSCRIPTION_ID=${{ fromJson(secrets.AZURECONNECTION).subscriptionId }}" >> $GITHUB_ENV
        echo "ARM_TENANT_ID=${{ fromJson(secrets.AZURECONNECTION).tenantId }}" >> $GITHUB_ENV

    - name: Terraform Init
      run: |
        cd Environment/QA
        terraform init

    - name: Terraform Plan
      run: |
        cd Environment/QA
        terraform plan

    - name: Terraform Apply
      run: |
        cd Environment/QA
        terraform apply --auto-approve

    - name: Terraform Destroy
      run: |
        cd Environment/QA
        terraform destroy --auto-approve
