name: InfraPipleineforAzure.yaml
on: [workflow_dispatch]
jobs:
  terraformjob:
   name: infra-provision
   runs-on:  self-hosted
   steps:

########### clean runner temp directory for clean installation ###################
     - name: Terraformversioncheck
       run: |
         terraform --version
       
      
################ check Directory #################################    
     - name: Checkout
       uses: actions/checkout@v4.2.2
################# Terraform init on Working directory ############
     - name: Terraform plan
       run: |
         cd Environment
         ls
         cd QA
         terraform init
################## Azure Authentication ####################
     - name: AzureAuthentication
       uses: azure/login@v2
       with:
          creds: ${{ secrets.AZURECONNECTION }}
       
################ Terraform plan ##############
     - name: Terraform Plan
       run:  |
         cd Environment/QA
         terraform plan

################ Terraform plan ##############
     - name: Terraform Apply
       run:  |
          cd Environment/QA
          terraform apply
                        
    
         
              
              
          
          
