name: InfraPipleineforAzure.yaml
on: [workflow_dispatch]
jobs:
  terraformjob:
   name: infra-provision
   runs-on:  self-hosted
   steps:

################ check Directory #################################    
     - name: Checkout
       uses: actions/checkout@v4.2.2
       
########### clean runner temp directory for clean installation ###################

          
     - name: Terraformversioncheck
       run: |
         terraform --version
       
     - name: AzureAuthentication
       uses: azure/login@v2
       with:
          creds: ${{secrets.AZURECONNECTION}}   

################# Terraform init on Working directory ############
    

     - name: Terraform init
       run: |
              cd Environment
              ls
              cd QA
              terraform init
      
################ Terraform plan ##############
     - name: Terraform Plan
       run:  |
         cd Environment/QA
         terraform plan

################ Terraform plan ##############
     - name: Terraform Apply
       run:  |
          cd Environment/QA
          terraform apply  --auto-approve
################ Terraform plan ##############
     - name: Terraform destroy
       run:  |
          cd Environment/QA
          terraform destroy  --auto-approve
                 
                        
    
         
              
              
          
          
