name: azureinfraBygithubaction

on:
  workflow_dispatch:  # Manual trigger only (same as "trigger: none")

jobs:
  infraprovision:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7  # Or whatever version you need
          
      - name: Azure Login action
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Terraform init azurerm backend
        
        uses: ahmedig/terraform-azurerm-backend@v4
        with:   
           azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}    
           resource_group_name: testrg   
           container_name: tfstatecontainer
           storage_account_name: tfstatestorageacc24      
           subscription_id: dcb52f24-3382-4902-9301-084ebd8ec819
                
           tf_working_directory: ./Environment/QA
                      
                      
      
            
