name: InfraPipleineforAzure.yaml
on: [workflow_dispatch]
jobs:
  terraformjob:
   name: infra-provision
   runs-on:  self-hosted
   steps:

########### clean runner temp directory for clean installation ###################
     - name: Clean temp folder
       run: Remove-Item -Path $env:RUNNER_TEMP\* -Recurse -Force -ErrorAction SilentlyContinue
       shell: pwsh
################ Terraform Tool install #################################     
     - name: Terraform installer
       uses: autero1/action-terraform@v3.0.1
       with:
          # Terraform version to install
          terraform-version: 1.10.3
          
          
          
          
