name: myfirstworkflow_in_yaml
run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}
on: 
  workflow_dispatch:
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - run: echo Hello world!
